name: sRPG
main: com.behindthemirrors.minecraft.sRPG.SRPG
version: 0.5alpha3

commands:
  srpg:
    description: Get status and help for the sRPG plugin
    usage: |
           /<command> status
           /<command> help [topic]
           /<command> [skillname]
           /<command> locale [locale]