name: sRPG
main: com.behindthemirrors.minecraft.sRPG.SRPG
version: 0.5alpha3

commands:
  srpg:
    description: Get status and help for the sRPG plugin
    usage: |
           /<command> status
           /<command> help [topic]
           /<command> [skillname]
           /<command> locale [locale]
permissions:
  srpg.basic:
    default: true
    description: Gives access to all normal features
    children:
      srpg.xp: true
  srpg.xp:
    description: gain xp
  srpg.admin:
    default: op
    description: Gives access to admin commands
    children:
      srpg.reload: true
  srpg.reload:
    description: reload config from ingame
  srpg.skills:
    description: Gives access to all skills
    children:
      srpg.skills.swords: true
      srpg.skills.swords.active: true
      srpg.skills.pickaxes: true
      srpg.skills.pickaxes.active: true
      srpg.skills.axes: true
      srpg.skills.axes.active: true
      srpg.skills.shovels: true
      srpg.skills.shovels.active: true
      srpg.skills.hoes: true
      srpg.skills.bow: true
      srpg.skills.ukemi: true
      srpg.skills.evasion: true
      srpg.skills.focus: true
  srpg.skills.passive:
    default: true
    description: Gives access to all passive skills
    children:
      srpg.skills.swords: true
      srpg.skills.pickaxes: true
      srpg.skills.axes: true
      srpg.skills.shovels: true
      srpg.skills.hoes: true
      srpg.skills.bow: true
      srpg.skills.ukemi: true
      srpg.skills.evasion: true
      srpg.skills.focus: true
  srpg.skills.swords:
    description: Passive skill
  srpg.skills.swords.active:
    description: Active abilities for the passive skill
  srpg.skills.pickaxes:
    description: Passive skill
  srpg.skills.pickaxes.active:
    description: Active abilities for the passive skill
  srpg.skills.axes:
    description: Passive skill
  srpg.skills.axes.active:
    description: Active abilities for the passive skill
  srpg.skills.shovels:
    description: Passive skill
  srpg.skills.shovels.active:
    description: Active abilities for the passive skill
  srpg.skills.hoes:
    description: Passive skill
  srpg.skills.bow:
    description: Passive skill
  srpg.skills.ukemi:
    description: Passive skill
  srpg.skills.evasion:
    description: Passive skill
  srpg.skills.focus:
    description: Passive skill
