combat:
  crit-chance: 0.05
  crit-multiplier: 2.0
  miss-chance: 0.0
  miss-multiplier: 0.0
  armor-multipliers: # not used yet
    leather: 1.0
    iron: 1.2
    gold: 1.2
    diamond: 1.5

stats:
  # named difficulty in basic config uses the values that have the same list index as the name
  difficulties: [default,original,custom]
  
  # MAKE SURE DIFFICULTY NAME IS THE SAME EVERYWHERE
  # damage values not in hearts (1 heart = 2 damage)
  default:
    animals:
      pig:
        health: 12
        xp: 1
      sheep:
        health: 12
        xp: 1
      chicken:
        health: 4
        xp: 1
      cow:
        health: 16
        xp: 1
      squid:
        health: 8
        xp: 1
    monsters:
      zombie:
        health: 40
        damage: 5
        xp: 10
      spider:
        health: 24
        damage: 3
        xp: 10
      skeleton:
        health: 12
        damage: 6
        xp: 10
      creeper:
        health: 16
        damage: 21
        xp: 20
      pigzombie:
        health: 30
        damage: 7
        xp: 20
      slime:
        huge:
          health: 64
          damage: 8
          xp: 20
        big:
          health: 16
          damage: 4
          xp: 10
        normal:
          health: 4
          damage: 2
          xp: 10
        small:
          health: 1
          damage: 1
          xp: 10
      wolf: 
        wild:
          health: 12
          damage: 4
          xp: 10
        tamed:
          health: 20
          damage: 3
          xp: 10
    tools:
      swords:
        wood:
          damage: 3
        stone:
          damage: 4
        iron:
          damage: 6
        gold:
          damage: 3
        diamond:
          damage: 8
      pickaxes:
        wood:
          damage: 2
        stone:
          damage: 3
        iron:
          damage: 4
        gold:
          damage: 2
        diamond:
          damage: 5
      axes:
        wood:
          damage: 2
        stone:
          damage: 3
        iron:
          damage: 5
        gold:
          damage: 2
        diamond:
          damage: 7
      shovels:
        wood:
          damage: 2
        stone:
          damage: 3
        iron:
          damage: 4
        gold:
          damage: 2
        diamond:
          damage: 5
      hoes: 
        wood:
          damage: 1
        stone:
          damage: 1
        iron:
          damage: 1
        gold:
          damage: 1
        diamond:
          damage: 1
      bow:
        damage: 1
      fists:
        damage: 1
          
  # MAKE SURE DIFFICULTY NAME IS THE SAME EVERYWHERE
  # damage values not in hearts (1 heart = 2 damage)
  original:
    animals:
      pig:
        health: 10
        xp: 1
      sheep:
        health: 10
        xp: 1
      chicken:
        health: 4
        xp: 1
      cow:
        health: 10
        xp: 1
      squid:
        health: 10
        xp: 1
    monsters:
      zombie:
        health: 20
        damage: 5
        xp: 1
      spider:
        health: 20
        damage: 2
        xp: 1
      skeleton:
        health: 20
        damage: 4
        xp: 1
      creeper:
        health: 20
        damage: 16
        xp: 1
      pigzombie:
        health: 20
        damage: 6
        xp: 1
      slime:
        huge:
          health: 32
          damage: 1
          xp: 1
        big:
          health: 16
          damage: 1
          xp: 1
        normal:
          health: 4
          damage: 1
          xp: 1
        small:
          health: 1
          damage: 1
          xp: 1
      wolf: 
        wild:
          health: 8
          damage: 2
          xp: 1
        tamed:
          health: 20
          damage: 4
          xp: 1
    tools:
      swords:
        wood:
          damage: 5
        stone:
          damage: 7
        iron:
          damage: 9
        gold:
          damage: 5
        diamond:
          damage: 11
      pickaxes:
        wood:
          damage: 3
        stone:
          damage: 4
        iron:
          damage: 5
        gold:
          damage: 3
        diamond:
          damage: 6
      axes:
        wood:
          damage: 4
        stone:
          damage: 5
        iron:
          damage: 6
        gold:
          damage: 4
        diamond:
          damage: 7
      shovels:
        wood:
          damage: 2
        stone:
          damage: 3
        iron:
          damage: 4
        gold:
          damage: 2
        diamond:
          damage: 5
      hoes: 
        wood:
          damage: 2
        stone:
          damage: 2
        iron:
          damage: 2
        gold:
          damage: 2
        diamond:
          damage: 2
      bow:
        damage: 4
      fists:
        damage: 2
        
  # MAKE SURE DIFFICULTY NAME IS THE SAME EVERYWHERE
  # damage values not in hearts (1 heart = 2 damage)
  custom:
    animals:
      pig:
        health: 1
        xp: 1
      sheep:
        health: 1
        xp: 1
      chicken:
        health: 1
        xp: 1
      cow:
        health: 1
        xp: 1
      squid:
        health: 1
        xp: 1
    monsters:
      zombie:
        health: 1
        damage: 1
        xp: 1
      spider:
        health: 1
        damage: 1
        xp: 1
      skeleton:
        health: 1
        damage: 1
        xp: 1
      creeper:
        health: 1
        damage: 1
        xp: 1
      pigzombie:
        health: 1
        damage: 1
        xp: 1
      slime:
        huge:
          health: 1
          damage: 1
          xp: 1
        big:
          health: 1
          damage: 1
          xp: 1
        normal:
          health: 1
          damage: 1
          xp: 1
        small:
          health: 1
          xp: 1
      wolf: 
        wild:
          health: 1
          damage: 1
          xp: 1
        tamed:
          health: 1
          damage: 1
          xp: 1
    tools:
      swords:
        wood:
          damage: 1
        stone:
          damage: 1
        iron:
          damage: 1
        gold:
          damage: 1
        diamond:
          damage: 1
      pickaxes:
        wood:
          damage: 1
        stone:
          damage: 1
        iron:
          damage: 1
        gold:
          damage: 1
        diamond:
          damage: 1
      axes:
        wood:
          damage: 1
        stone:
          damage: 1
        iron:
          damage: 1
        gold:
          damage: 1
        diamond:
          damage: 1
      shovels:
        wood:
          damage: 1
        stone:
          damage: 1
        iron:
          damage: 1
        gold:
          damage: 1
        diamond:
          damage: 1
      hoes: 
        wood:
          damage: 1
        stone:
          damage: 1
        iron:
          damage: 1
        gold:
          damage: 1
        diamond:
          damage: 1
      bow:
        damage: 1
      fists:
        damage: 1
      
  damage:
    depth:
      thresholds: [40,15]
      damage-increase: [1,2]

xp:
  to-levelup: 1000
  blocks:
    xp-groups: [common, uncommon, rare]
    default-group: common
    # everything that is not in one of the other groups defaults to the default group
    
    common: 
      xp: 1
      chance: 0.05
    uncommon:
      ids: [16,73,74,82,89,49]
      xp: 1
      chance: 0.3
    rare:
      ids: [14,15,56,21]
      xp: 5
      chance: 1.0
      
skills:
  costs: 
    generic: [1,1,1,2,2,2,3,3,3,5,7]
    focus-base: 10
    focus-increase: 2
  milestones:
    novice: 0
    apprentice: 4
    expert: 7
    master: 11
  effects:
    swords:
      durability-recovery-chance: 0.02
      milestone-bonus: 0.01
    pickaxes:
      durability-recovery-chance: 0.02
      milestone-bonus: 0.01
    axes:
      durability-recovery-chance: 0.02
      milestone-bonus: 0.01
    shovels:
      durability-recovery-chance: 0.02
      milestone-bonus: 0.01
    hoes:
      durability-recovery-chance: 0.02
      milestone-bonus: 0.01
    bow:
      crit-chance: 0.02
      milestone-bonus: 0.01
    ukemi:
      autoroll-chance: 0.02
      milestone-bonus: 0.01
      roll-window: 100 # [ms]
    evasion:
      chance: 0.02
      milestone-bonus: 0.01
    focus:
      boost: 0.05
  passive-abilities: 
    swords:
      apprentice:
        parry-chance: 0.1
      expert: 
        parry-chance: 0.05
        crit-chance: 0.1
      master: 
        crit-chance: 0.1
        crit-multiplier: 1
    pickaxes:
      apprentice: 
        double-drop-chance: 0.05
      expert:
        double-drop-chance: 0.1
      master:
        double-drop-chance: 0.05
        triple-drop-chance: 0.05
    axes:
      apprentice: 
        double-drop-chance: 0.05
      expert:
        double-drop-chance: 0.1
      master:
        double-drop-chance: 0.05
        triple-drop-chance: 0.05
    shovels:
      apprentice:
        common-drop-chance: 0.04
      expert:
        uncommon-drop-chance: 0.02
      master: 
        rare-drop-chance: 0.005
    bow: 
      apprentice: 
        damage-modifier: 1
      expert: 
        crit-multiplier: 1
      master: 
        damage-modifier: 1
        crit-multiplier: 1
    ukemi: # values here not used yet
      apprentice: 
        fall-height-increase: 1
      expert: 
        fall-height-increase: 1
      master: 
        fall-height-increase: 1
    evasion: # values here not used yet
      apprentice: 
        explosion-escape-chance: 0.2
      expert: 
        arrow-catch-chance: 0.2
      master: 
        counterattack-chance: 0.2
  
abilities:
  max-charges: 11
  blocks-to-charge: 64
  costs:
    swords:
      stone: 1
      iron: 1
      diamond: 1
    pickaxes:
      stone: 1
      iron: 1
      diamond: 1
    axes:
      stone: 1
      iron: 1
      diamond: 1
    shovels:
      stone: 1
      iron: 1
      diamond: 1
        
item-requirements:
  untrained-miss-chance: 0.2
  untrained-damage-modifier: -1
  untrained-durability-loss: 4
  swords:
    wood: 0
    stone: 0
    iron: 3
    gold: 7
    diamond: 4
  pickaxes:
    wood: 0
    stone: 0
    iron: 3
    gold: 7
    diamond: 4
  axes:
    wood: 0
    stone: 0
    iron: 3
    gold: 7
    diamond: 4
  shovels:
    wood: 0
    stone: 0
    iron: 3
    gold: 7
    diamond: 4
  hoes: 
    wood: 0
    stone: 0
    iron: 3
    gold: 7
    diamond: 4
  bow: 0
