combat:
  restrictions:
    enabled: false
    group-prefix: groups.
    groups:
      # group1: [group1,group3,animals,monsters]
      # group2: [group1,animals]
settings:
  blocks:
    groups:
      # you can add/remove/rename as many groups as you like apart from 'default'
      # everything that is not explicitely assigned a group gets assigned 'default'
      default: # again: do not remove this group
        xp: 1
        chance: 0.33
        charge-ticks: 1
      uncommon:
        materials: []
        xp: 1-2
        chance: 0.66 
        charge-ticks: 2
      rare:
        materials: []
        xp: 2-5
        charge-ticks: 5
  charges:
    ticks-to-charge: 64
    ticks:
      combat-hit: 1
      combat-kill: 5
      
