settings:
  xp:
    # xp for next level are equal to 
    # (base * level-coefficient * ((current level) ** level-exponent) * tier-coefficient * ((the jobs tier) ** tier-exponent) + (current level) * offset * (the jobs tier))
    
    base: 1000
    offset: 0
    level-coefficient: 1.2 
    level-exponent: 1
    tier-coefficient: 1 
    tier-exponent: 1
  
  # singular and plural endings specified in brackets '()' separated by a pipe '|'
  defaults: # may be modified by specific jobs under the node 'base-stats'
    maximum-level: 10
    crit-chance: 0.02
    crit-multiplier: 1.5
    miss-chance: 0.05
    miss-multiplier: 0.0

job-prefixes:
  Level 1: Novice
  Level 4: Trained
  Level 7: Expert
  Level 10: "[gold]Master"

job-terminology:
  job: Job(|s)
  passive: Skill(|s)
  active: Abilit(y|ies)
  level: Level(|s)

# New users get assigned one of the jobs with empty 'prerequisites' nodes at random (by default only the 'adventurer' job has an empty 'prerequisites' node
tree:
  adventurer:
    prerequisites:
  archer:
    prerequisites: 
      adventurer: 1
  sniper:
    prerequisites:
      archer: 3
