mySQL:
  enabled: false
  server: localhost
  port: 3306
  dbName: name
  dbUser: user
  dbPass: pass
  table_prefix: srpg_
settings:
  disabled-worlds: [] # plugin won't do anything on worlds listed in here
  combat:
    difficulty: default # creates a new .yml from default if the named difficulty is unavailable
    dangerous-depths: true # increases damage by monsters lower certain depths
  locales: # add all localized localization_XX.ymls you want to make available here
    default: EN # creates a new .yml from default if the named locale is unavailable
    available: [EN] # players will be able to choose from the locales listed in here
debuggers: [zaph34r]