#################################################################################
# MARKUP DESCRIPTION #
######################
# every '[' is replaced by the color tag for the configured emphasis color
# every ']' is replaced by the color tag for the set default text color
# references to nodes insides the 'effects' node can be used in angled brackets
# referenced values will be strings, unless a conversion specification is given
# use like: '<effect.node:convert-to>'
# 'effect' refers to any effect inside the 'effects' node of the skill
# 'node' refers to any node inside the given effect
# 'convert-to' can be any one of: percent,hearts
# example:
# 
# some-skill:
#   name: Some random example skill
#   description: "[+<crit-chance.value:percent>] percentage to [crit]"
#   effects: 
#     crit-chance:
#       tools: [swords,axes]
#       value: 0.2'
#     some-other-effect:
#       [...]
#
# Also remember to put the description into double quotes if there is a conversion specification, else the ':' breaks the parser
# 
#################################################################################

#####################
# TRAITS & PASSIVES #
#####################

from-behind:
  name: From Behind
  description: 
  effects:
    boost: 
      name: crit-chance
      tools: [swords,axes,pickaxes,hoes]
      conditions: [backstab-offensive]
      value: 0.50
      level-based: [value]

target-vitals:
  name: Target Vitals
  description: 
  effects:
    boost: 
      name: crit-multiplier
      value: 0.5
      tools: [swords,axes,pickaxes,hoes]
      conditions: [backstab-offensive]

ranged-focus:
  name: Ranged Combat Focus
  description: 
  effects:
    boost:
      name: crit-chance
      tools: [bow]
      value: 0.1
      level-based: [value]
    boost1:
      name: damage-modifier
      tools: [swords,axes]
      value: -2
    boost2:
      name: crit-chance
      tools: [swords,axes]
      value: -0.05
      
snipers-eye:
  name: Sniper's eye
  description:
  effects:
    boost:
      tools: [bow]
      name: crit-multiplier
      value: 0.5
      level-based: [value]

enhanced-aim:
  name: Enhanced Aim
  description:
  effects:
    boost:
      tools: [bow]
      name: miss-chance
      value: -0.05

footwork:
  name: Footwork
  description:
  effects:
    boost:
      name: evade-chance
      value: 0.1
      level-based: [value]

parry:
  name: Parry
  description:
  effects:
    boost:
      name: parry-chance
      value: 0.05
      tools: [swords]
    boost1:
      name: parry-efficiency
      value: 0.3
      tools: [swords]

defensive-sword-training:
  name: Defensive Sword Training
  description: 
  effects: 
    boost: 
      name: parry-chance
      value: 0.2
      tools: [swords]

improved-parry:
  name: Improved Parry
  description:
  effects:
    boost:
      name: parry-efficiency
      value: 0.2
      tools: [swords]

offensive-sword-training:
  name: Offensive Sword Training
  description:
  effects:
    boost: 
      name: damage-modifier
      value: 1
      tools: [swords]

improved-accuracy:
  name: Improved Accuracy
  description: 
  effects:
    boost:
      tools: [bow]
      name: target-evade-chance
      value: -0.1
    boost1:
      tools: [bow]
      name: target-evade-efficiency
      value: -0.1

riposte:
  name: Riposte
  description: 
  effects:
    trigger-active:
      triggers: [combat]
      conditions: [parry-defensive]
      chance: 0.5
      tools: [swords]
      action: focus
    direct-damage:
      conditions: [parry-defensive]
      chance: 0.5
      self: false
      target: true
      value: 2

read-the-wind:
  name: Read the Wind
  description: 
  effects: 
    set-combat-state: 
      tools: [bow]
      conditions: [highground-offensive]
      miss: false 
    boost: 
      tools: [bow]
      name: crit-chance
      value: 0.25

lucky-shots:
  name: Lucky Shots
  description: 
  effects: 
    boost:
      tools: [bow]
      conditions: [crit-offensive]
      crit-multiplier: 1.0
      chance: 0.5
      
bow-training:
  name: Bow Training
  description: 
  effects: 
    boost:
      tools: [bow]
      name: damage-modifier
      value: 1
      
ballistics:
  name: Ballistics
  description: Increased damage when attacking from higher ground
  effects:
    boost: 
      tools: [bow]
      name: damage-modifier
      value: 2
      conditions: [highground-offensive]

deadly-arrows:
  name: Deadly Arrows
  description: 
  effects:
    boost:
      name: crit-chance
      value: 1.0
  replaces: poisoned-arrows

poisoned-arrows:
  name: Poisoned Arrows
  description: 
  effects:
    trigger-active:
      triggers: [combat]
      chance: 0.5
      action: apply-poison
      conditions: [attacking]

tool-proficiency:
  name: Tool Proficiency
  effects:
    boost: 
      name: durability-recovery-chance
      value: 0.3
      level-based: [value]
      tools: [axes,pickaxes,hoes]

lumberjack:
  name: Lumberjack
  effects:
    drop-change:
      mode: multiply
      chance: 0.3
      level-based: [chance]
      tools: [axes]
      versus: [log]

stonecutter:
  name: Stonecutter
  effects: 
    drop-change:
      mode: multiply
      chance: 0.3
      level-based: [chance]
      tools: [pickaxes]
      versus: [stone]

coal-mining:
  name: Coal Mining
  effects:
    drop-change:
      mode: add
      chance: 0.01
      tools: [pickaxes]
      versus: [stone]
      items: [coal]
      amounts: [1]
    drop-change1:
      mode: multiply
      chance: 0.15
      level-based: [chance]
      tools: [pickaxes]
      versus: [coal_ore]

#########
# BUFFS #
#########

sift-resources:
  name: Sift Resources
  adjective: searching for resources
  effects:
    drop-change:
      tools: [nothing]
      versus: [grass,dirt,gravel]
      mode: add
      items: [seeds,string,feather,sulphur,flint,clay_ball,redstone]
      amounts: [1,1,1,1,1,1]
      chance: 0.3
      all: false

sift-valuables:
  name: Sift Resources
  adjective: searching for valuables
  effects:
    drop-change:
      tools: [nothing]
      versus: [grass,dirt,gravel]
      mode: add
      items: [coal,arrow,stick,iron_ingot,gold_ingot,diamond]
      amounts: [1,1,1,1,1,1]
      chance: 0.15
      all: false

bleed:
  name: Bleed
  adjective: bleeding
  effects:
    direct-damage:
      value: 1
      # attribute: physical
    
focus:
  name: Focus
  adjective: focused
  effects:
    boost:
      name: damage-modifier
      value: 1
      
blind:
  name: Blind
  description: 
  adjective: blinded
  effects: 
    boost:
      name: miss-chance
      value: 0.1

elusive:
  name: Elusive
  description: 
  adjective: elusive
  effects:
    boost: 
      name: target-miss-chance
      value: 0.1

concentration:
  name: Concentration
  description: 
  adjective: concentrating
  effects: 
    boost: 
      name: target-evade-chance
      value: -0.2
    boost: 
      name: target-parry-chance
      value: -0.2
    boost: 
      name: target-chance
      value: -0.2

reinforced-bowstring:
  name: Reinforced Bowstring
  effects:
    boost:
      name: max-damage-modifier
      value: 4
      tools: [bow]

invincibility:
  name: Invincibility
  description: 
  #adjective: invincible
  effects: 
    set-combat-state:
      self: false
      target: true
      canceled: true

rage:
  name: Rage
  description: 
  adjective: enraged
  effects: 
    set-combat-state:
      crit: true
      
poison:
  name: Poison
  description:
  adjective: poisoned
  effects:
    direct-damage:
      value: 1
      #attribute: poison
      
weak-poison:
  name: Weak Poison
  description:
  adjective: weakly poisoned
  effects:
    direct-damage:
      value: 1
      chance: 0.5
      #attribute: poison

###################
# EVERYTHING ELSE #
###################

#############
# DEBUGGING #
#############

backstab1:
  name: Backstab (dummy)
  effects:
    set-combat-state:
      conditions: [backstab-offensive]
      crit: true

heightshot1:
  name: Higher Ground (dummy)
  effects:
    set-combat-state:
      tools: [bow]
      conditions: [highground-offensive]
      crit: true
      
dropnight1:
  name: Drop Gold (dummy)
  effects:
    drop-change:
      conditions: [night]
      versus: [stone]
      mode: replace
      items: [gold_ingot]
      amounts: [5]
  
dropday1:
  name: Drop Iron (dummy)
  effects:
    drop-change:
      conditions: [day]
      versus: [stone]
      mode: replace
      items: [iron_ingot,coal]
      amounts: [3,5]
      all: false

losearmor1:
  name: Lose Armor (dummy)
  effects:
    trigger-active:
      triggers: [move]
      from: [SNOW]
      versus: [stone,dirt]
      tools: [swords]
      action: droparmor

losearmor2:
  name: Lose Armor (dummy)
  effects:
    trigger-active:
      triggers: [daybreak]
      from: [grass]
      action: droparmor